const FETCH_EXPENSES = 'expenses/FETCH_EXPENSES';
const SAVE_EXPENSES = 'expenses/SAVE_EXPENSES';
const TOGGLE_EDIT_EXPENSE = 'expenses/TOGGLE_EDIT_EXPENSE';
const UPDATE_EXPENSE = 'expenses/UPDATE_EXPENSE';
const DELETE_EXPENSE = 'expenses/DELETE_EXPENSE';
const CREATE_EXPENSE = 'expenses/CREATE_EXPENSE';

export {
  FETCH_EXPENSES,
  SAVE_EXPENSES,
  TOGGLE_EDIT_EXPENSE,
  UPDATE_EXPENSE,
  DELETE_EXPENSE,
  CREATE_EXPENSE,
};
