const FETCH_EXPENSES = 'expenses/FETCH_EXPENSES';
const SAVE_EXPENSES = 'expenses/SAVE_EXPENSES';
const SET_EDIT_EXPENSE_ID = 'expenses/SET_EDIT_EXPENSE_ID';
const UPDATE_EXPENSE = 'expenses/UPDATE_EXPENSE';
const DELETE_EXPENSE = 'expenses/DELETE_EXPENSE';
const CREATE_EXPENSE = 'expenses/CREATE_EXPENSE';

export {
  FETCH_EXPENSES,
  SAVE_EXPENSES,
  SET_EDIT_EXPENSE_ID,
  UPDATE_EXPENSE,
  DELETE_EXPENSE,
  CREATE_EXPENSE,
};
